export const phenomics = {
  "total": 20,
  "rows": [
      {
          "xotId": 1155,
          "uid": "ZX01aAGRDIS000001",
          "category": "disease",
          "type": "GLS",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-GLS_Blup",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1156,
          "uid": "ZX01aAGRDIS000002",
          "category": "disease",
          "type": "MRDV",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-MRDV_6Env-BLUP",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1157,
          "uid": "ZX01aAGRDIS000003",
          "category": "disease",
          "type": "MRDV",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-MRDV_7Env-BLUP",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1158,
          "uid": "ZX01aAGRDIS000004",
          "category": "disease",
          "type": "MRDV",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-MRDV_Blup",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1159,
          "uid": "ZX01aAGRDIS000005",
          "category": "disease",
          "type": "NLB",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-NLB_Blup",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1160,
          "uid": "ZX01aAGRDIS000006",
          "category": "disease",
          "type": "NLB",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-NLBlength",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1161,
          "uid": "ZX01aAGRDIS000007",
          "category": "disease",
          "type": "NLB",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-NLBwidth",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1162,
          "uid": "ZX01aAGRDIS000008",
          "category": "disease",
          "type": "SCMV",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-SCMV",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1163,
          "uid": "ZX01aAGRDIS000009",
          "category": "disease",
          "type": "SCR",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-SCR_Blup",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1164,
          "uid": "ZX01aAGRDIS000010",
          "category": "disease",
          "type": "SLB",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-SLB_Blup",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1165,
          "uid": "ZX01aAGRDIS000011",
          "category": "disease",
          "type": "GLS",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-GLS_11DH",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1166,
          "uid": "ZX01aAGRDIS000012",
          "category": "disease",
          "type": "GLS",
          "analysis": "ZA02aPHE000002",
          "name": "Disease-GLS_12DH",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1167,
          "uid": "ZX01aAGRFLO000001",
          "category": "flowering",
          "type": "days_to_pollen",
          "analysis": "ZA02aPHE000003",
          "name": "Agro2-Days_To_Pollen_BLUP",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1168,
          "uid": "ZX01aAGRFLO000002",
          "category": "flowering",
          "type": "days_to_pollen",
          "analysis": "ZA02aPHE000003",
          "name": "Agro2-Days_To_Silking_BLUP",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1169,
          "uid": "ZX01aAGRFLO000003",
          "category": "flowering",
          "type": "heading_date",
          "analysis": "ZA02aPHE000003",
          "name": "Agro-Headingdate",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1170,
          "uid": "ZX01aAGRFLO000004",
          "category": "flowering",
          "type": "heading_date",
          "analysis": "ZA02aPHE000003",
          "name": "Agro2-Heading_Date_BLUP",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1171,
          "uid": "ZX01aAGRFLO000005",
          "category": "flowering",
          "type": "heading_date",
          "analysis": "ZA02aPHE000003",
          "name": "Agro-Pollenshed",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1172,
          "uid": "ZX01aAGRFLO000006",
          "category": "flowering",
          "type": "heading_date",
          "analysis": "ZA02aPHE000003",
          "name": "Agro-Silkingtime",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1173,
          "uid": "ZX01aAGRFLO000007",
          "category": "flowering",
          "type": "days_to_pollen",
          "analysis": "ZA02aPHE000003",
          "name": "Agro2-Days_To_Pollen_CQ2011",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      },
      {
          "xotId": 1174,
          "uid": "ZX01aAGRFLO000008",
          "category": "flowering",
          "type": "days_to_pollen",
          "analysis": "ZA02aPHE000003",
          "name": "Agro2-Days_To_Silking_CQ2011",
          "location": "Yunnan",
          "traitDateLoc": "BLUP",
          "year": "2014",
          "tissue": "Whole"
      }
  ],
  "code": 200,
  "msg": "查询成功"
}